[package]
name = "runn"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.33", features = ["serde-serialize"] }
log = "0.4"
env_logger = "0.10"
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"                                              # Or any other format you want to use
rmp-serde = "1.3.0"
typetag = "0.2"
special = "0.11.3"
csv = "1.1"
tensorboard-rs = "0.5.9"                                        # Use the latest version available
tempfile = "3.19.1"
rayon = "1.7"

[profile.release]
opt-level = 3 # Optimization level (0-3, s, z)
lto = true    # Enable Link Time Optimization
debug = false # Disable debug information
